# Generated by Django 3.1.4 on 2021-03-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
