# Generated by Django 3.1.4 on 2021-03-04 18:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20210304_1850'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Porduct', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={'verbose_name': 'Promotion', 'verbose_name_plural': 'Promotions'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.promotion', verbose_name='Promotion'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 18, 50, 57, 157243), verbose_name='Expires'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='stores.store', verbose_name='Store'),
        ),
    ]
