# Generated by Django 3.1.4 on 2021-03-04 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210304_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 4, 19, 0, 19, 570080), verbose_name='Expires'),
        ),
    ]
