# Generated by Django 3.1.4 on 2021-03-10 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210304_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 10, 21, 40, 48, 933704), verbose_name='Expires'),
        ),
    ]
